manifest:
  remotes:
    - name: sadekbaroudi
      url-base: https://github.com/sadekbaroudi
    - name: taz
      url-base: https://github.com/thazhemadam
  projects:
    - name: zmk-fingerpunch-vik
      remote: taz
      revision: zmk-v4.1/drop-cirque-input-module
      import: config/deps.yml
    - name: zmk-fingerpunch-controllers
      remote: sadekbaroudi
      revision: main
      import: config/deps.yml
